### PR TITLE
Updated light turret multiblock

### PR DESCRIPTION
**Pull request by ItsAlreadyGold**
I'm not sure if I did everything right so please check real quick

### CODE REVIEW

**Comment by trainb0y1** [comment]
I get the feeling that Peter is going to say to import Material.grindstone directly.

**Comment by trainb0y1** [comment]
Closes https://github.com/HorizonsEndMC/IonCore/issues/55 I think?

**Comment by ItsAlreadyGold** [comment]
I'll do the rest of them, but you and peter will need to do anything I miss in it

**Comment by ItsAlreadyGold** [comment]
Also, yall will need to remove the thing where you can click on the turret sign to hop in the turret cockpit. There wont be a turret cockpit anymore, and turrets shouldn't be controllable as a result

**Review by Peter-Crawley — APPROVED** [review]
lgtm

**Comment by trainb0y1** [comment]
https://github.com/HorizonsEndMC/IonCore/pull/64/commits/55912c3bdfad291083ab7da9d619ca95e59cd7cd Lol I was right

**Pull request merged**
