### PR TITLE
Fix old SL map link

### PR DESCRIPTION
**Pull request by Gutin1**

### CODE REVIEW

**Comment by trainb0y1** [comment]
https://github.com/HorizonsEndMC/IonCore/pull/80 lol I tried to do this yesterday

**Comment by Gutin1** [comment]
Ah, didn't see it between resource pack updates, I'll close mine.

**Comment by trainb0y1** [comment]
Doesn’t matter, the prs are identical, idc

**Comment by trainb0y1** [comment]
As long as the stupid link gets fixed

**Pull request closed without merging**
